### ISSUE TITLE
Social media links and accounts

### ISSUE THREAD

**Issue by jradtilbrook** [curtinrobotics/curtinrobotics.github.io#3]
Do we link to social media sites? What does the club have?

**Comment by jradtilbrook** [comment]
@Tapego This is actually already live. Can you check it out and tell me what you think? [link](http://curtinrobotics.github.io/contact)

**Comment by Tapego** [comment]
Seems kind of minimal so we might need to mess with formatting a bit, as it is it's a large page with just a few lines on it. That being said, not really sure what to fill the rest of the page with. Might look at other contact pages to see what other websites have.

**Comment by jradtilbrook** [comment]
Yeah a little, but if I don't think its a big issue. I think its better than cramming it all on the footer or something.
Also we could embed google maps or a screenshot of google maps.
I take it that you want it there then?

**Comment by Tapego** [comment]
If we could embed Google Maps that would probably be best. I think I'll give it a shot but I don't know if I'll get far.
