### ISSUE TITLE
Figure out how to be found by google searches

### ISSUE THREAD

**Issue by jradtilbrook** [curtinrobotics/curtinrobotics.github.io#5]
Look into SEO and how google indexes websites.

**Comment by jradtilbrook** [comment]
this looks helpful [https://blog.kissmetrics.com/get-google-to-index/](https://blog.kissmetrics.com/get-google-to-index/)

**Comment by Tapego** [comment]
Well, here's a sitemap I generated with that website. It says it only includes links on the main page, but also looks simple enough to just edit with notepad or something like to add more links.
[sitemap.zip](https://github.com/curtinrobotics/curtinrobotics.github.io/files/234256/sitemap.zip)

**Comment by jradtilbrook** [comment]
@Tapego I think you should sign up for google analytics with the club email account: here are some links:
- https://analytics.google.com/analytics/web/provision?authuser=0#provision/SignUp/
- https://support.google.com/analytics/answer/1008015?hl=en

Then you can get some javascript to include on the site that will help with tracking and search indexing. Post the javascript here when you have it :smile:

**Comment by Tapego** [comment]
Not sure if this is exactly what you want, but here's what I got:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-77449484-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by jradtilbrook** [comment]
Okay cool I'll get this into master asap. After its live, you should be able to see traffic and analytics (if there would even be any) after a few hours. I think the only other thing that would help with SEO is to put it on the facebook group and make a post about it. Do you think its ready for that..?
