### ISSUE TITLE
Media content

### ISSUE THREAD

**Issue by jradtilbrook** [curtinrobotics/curtinrobotics.github.io#6]
https://www.youtube.com/watch?v=1mRr50VdnBs

**Comment by jradtilbrook** [comment]
I suppose this ties in with some of the other media related issues. Do you want to embed videos and photos from events/projects on a gallery page?

**Comment by jradtilbrook** [comment]
I suppose this ties in with some of the other media related issues. Do you want to embed videos and photos from events/projects on a gallery page?

**Comment by Tapego** [comment]
Yeah that sounds like a good idea, should I make a folder on Google Drive containing everything that we'd want up there?

**Comment by jradtilbrook** [comment]
@Tapego it depends on what you think is better. We could embed the folder (in icon view) so people can see the images, but we wouldn't really be able to do much else with them. This way would also reduce the repo size and potentially ease the control of what photos are shown (ie, just add photos to google drive, rather than update the website).

Otherwise we copy the images we want directly to the website and can do a slide show type thing that would look a bit nicer, but be a maybe be a bit harder to maintain. I could look into something that would combine both - making it easy to manage, and look nice also.

I think maybe a mixture of both might work well..?

**Comment by Tapego** [comment]
@jradtilbrook Yeah that could be good, if we could get a mixture where we have a slideshow that loads the images within Google Drive or something like that I'd imagine that'd be best and easiest to maintain.

**Comment by jradtilbrook** [comment]
Yeah that sounds best - I did try it previously, and it took a long time to load from Drive so maybe we could compress the images a bit more. Other than that it shouldn't be too hard - we'll see when I get to it

**Comment by Tapego** [comment]
I think I'll make a separate folder specifically for the website then and link it through here.

**Comment by Tapego** [comment]
[Okay so here's the link](https://drive.google.com/open?id=0B3zdoDC33IO_U3U4M1hjcWNXRUU), hopefully we should just be able to add and remove from that fairly easily.
