### ISSUE TITLE
Events page clean up

### ISSUE THREAD

**Issue by jradtilbrook** [curtinrobotics/curtinrobotics.github.io#7]
Fix following issues:
- remove private events
- fix up page heading
- right a small paragraph about events
- include link to minutes and/or signups and/or proposals (Luke's google forms)
  - can we embed google forms?

**Comment by jradtilbrook** [comment]
@Tapego This is pretty much done. If you want a form to suggest an event (and/or project) I just need the URL then it can go live. Otherwise, if you don't want an event suggestion form, I'll close this issue.

**Comment by Tapego** [comment]
I think we might just leave it so that people can contact our email if they want to suggest an event.
